### ISSUE TITLE
Overdepending on argparse

### ISSUE THREAD

**Issue by awvwgk** [qcscine/puffin#2]
[argparse](https://docs.python.org/3/library/argparse.html) is available in Python standard library and is only required for Python 3.2 and below, however it is listed in the `requirements.txt`:

https://github.com/qcscine/puffin/blob/566519fb4762c51e1c5b71a72829aa21f44cc25a/requirements.txt#L1

**Comment by weymutht** [comment]
Thanks for reporting this. We will remove this dependency in the next release.

**Comment by reiher-research-group** [comment]
This is resolved with Puffin 1.1.0, released today.
